[package]
name = "notitle"
version = "0.1.0"
authors = ["Ivan_HAN <hyf1996@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.15.3"
tokio = { version = "0.2", features = ["full"] }
